### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by ianmckenna87** [fstxz/prop_placer#12]
I'm enjoying the prospect of this plug-in so far, but one small suggestion I'd like to make it to remove the scene tools tab and have all the functionality contained within the collections tab (this would also work more similarly to a 2D tile map)

![image](https://github.com/user-attachments/assets/d69e95aa-15c1-4348-b278-ab616af4dfdf)

**Comment by fstxz** [comment]
It used to be like this before, but I recently removed the bottom panel entirely because it was buggy, hard to maintain and took too much space. The scene tools button is kinda necessary for temporarily disabling the plugin, because you don't always want it to be active, but maybe there is a better way of handling this...

**Comment by ianmckenna87** [comment]
I do think being able to preview assets in a panel is one of the biggest strengths of a plugin like this

**Comment by fstxz** [comment]
You can see previews in filesystem dock if you switch it to split mode and then to grid view (I also recommend moving the dock to bottom, otherwise there will be no space for split mode). Godot's previews are not very good, but I think there is a way to override them with a plugin, I will take a look.

**Comment by brohd11** [comment]
@fstxz
Old/closed post, but it seems the most relevant here.

I know it's been awhile, any interest in working on the plugin anymore?

I started integrating it with my plugin that displays previews using the file system and I've got it forwarding selected UIDs to your plugin as the 'backend'. The layout is customizable and you can also dock it in any spot

I don't have a collection system, it just uses the file system, though I don't think it would be too hard for me to implement one on my end.

I saw you had some expand-ability for more tools, I was interested in what other ideas you had.

I think you have a solid framework here, that seems to be simple to integrate with.

If you have any ideas for this let me know

https://github.com/user-attachments/assets/68882f67-afe0-4fc9-aae8-f0d6243da2af

**Comment by fstxz** [comment]
@brohd11 Hi there

> I know it's been awhile, any interest in working on the plugin anymore?

Well, the plugin does everything I need for my personal project, but if someone has a suggestion for a new feature I might consider implementing it.

> I started integrating it with my plugin that displays previews using the file system and I've got it forwarding selected UIDs to your plugin as the 'backend'. The layout is customizable and you can also dock it in any spot

Interesting!

> I don't have a collection system, it just uses the file system, though I don't think it would be too hard for me to implement one on my end.

Oh don't worry, the version in the master branch doesn't use collection system anymore, it uses filesystem directly. I haven't made a new release after removing collections because I was waiting for a PR to be merged into Godot that fixes an issue with the filesystem dock. It looks like the fix is included in Godot 4.4, so I might do a new release soon.

> I saw you had some expand-ability for more tools, I was interested in what other ideas you had.

I had a few ideas.

1. Instance painting. Useful for painting grass or trees. It would use [MultiMesh](https://docs.godotengine.org/en/stable/classes/class_multimesh.html) under the hood. Terrain3D plugin has this feature (https://terrain3d.readthedocs.io/en/latest/docs/instancer.html), but as far as I know, it can only paint on the terrain itself, you can't paint on other meshes.

2. Some kind of area painting system, where you could define trigger zones and paint them. Then you would define rules for triggering them, e.g. if body with the name "player" enters this area, call "switch_scene" function (or emit a signal, or some other stuff). This is just an idea, I'm not sure how useful it will be.
