### ISSUE TITLE
Rethink the UI

### ISSUE THREAD

**Issue by krazyjakee** [fstxz/prop_placer#7]
I'm not affiliated with cookiebadger or the assetplacer plugin.

I understand the implementation and features may vary slightly but such an obvious and direct ripoff of the UI is not a good look and not good for the Godot ecosystem. If every commercial asset is going to have an open source ripoff, the commercial ecosystem will simply die. That's bad for developers, gamers and the Godot project itself.

Please consider going back to the drawing board and coming up with a new UI for this plugin.

**Comment by fstxz** [comment]
Hey. This project is a continuation of [Prop Painter](https://github.com/gildedhipbone/prop_painter). I looked at Asset Placer a few times during development, just to see how they do the styling of certain UI elements because it looked professional, is there anything wrong with that? Ripping off was never my intention. I took the general layout from Prop Painter plugin.

> Please consider going back to the drawing board and coming up with a new UI for this plugin.

Keep in mind that I spent my free time working on this plugin without any malicious intent. You should not just demand something from me. I understand your concerns, but I am not gonna bother with this unless Asset Placer's dev says so or if YOU want to donate YOUR free time and come up with a completely different layout for this type of plugin.

**Comment by CookieBadger** [comment]
Hey, AssetPlacer dev here :)
I've been made aware of your plugin on Reddit today. I appreciate you looking at my plugin for inspiration, and if I have given you ideas, I am glad. I trust you that ripping off was not your intention. 

I would however appreciate it if (at least for future development) you think about how you can differentiate your plugin from AssetPlacer. I appreciate having open-source competition, especially if it helps low-budget developers. If somehow possible, I would only like to avoid having a "free clone" that looks exactly the same and does things the same way, since it does not really create new value and innovation, but only makes my development efforts worth less.

If you create a competitor plugin that establishes itself with its own identity and tries to do things better/different, then I'm all for it :)

I congratulate you on getting this far in developing a plugin, I know this is not an easy achievement!

**Comment by fstxz** [comment]
@CookieBadger Hey, thanks for commenting.

> I would however appreciate it if (at least for future development) you think about how you can differentiate your plugin from AssetPlacer.

I will rename this plugin to something without "Placer" and gradually change the UI so it looks less like yours. This is all I can do right now.

> If you create a competitor plugin that establishes itself with its own identity and tries to do things better/different, then I'm all for it :)

Well, this plugin in the early stages of development so it's hard to tell what it will become, but I will try my best to come up with unique and interesting features (if I don't get burned out maintaining an open source plugin and abandon it, of course).

> I congratulate you on getting this far in developing a plugin, I know this is not an easy achievement!

Thanks.
